# Generated by Django 3.2 on 2023-01-06 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_todo_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
